# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactnativecodepush' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactnativecodepush
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

  

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  target 'reactnativecodepushTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactnativecodepush-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactnativecodepush-tvOS

  target 'reactnativecodepush-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end